// TỰ SINH bởi scripts/gen-game-audio.py — đừng sửa tay, chạy lại script.
// Câu các trò chơi nói -> file mp3 đọc sẵn bằng Piper (xem docstring script).

export const GAME_CLIPS: Record<string, string> = {
  "Âm a": "/audio/tro-choi/am-a-157bfa.mp3",
  "Âm á": "/audio/tro-choi/am-a-cb8691.mp3",
  "Âm ớ": "/audio/tro-choi/am-o-261dc8.mp3",
  "Âm e": "/audio/tro-choi/am-e-1c4c5a.mp3",
  "Âm ê": "/audio/tro-choi/am-e-465a04.mp3",
  "Âm i": "/audio/tro-choi/am-i-3ea610.mp3",
  "Âm o": "/audio/tro-choi/am-o-5a6fb6.mp3",
  "Âm ô": "/audio/tro-choi/am-o-4cf01a.mp3",
  "Âm ơ": "/audio/tro-choi/am-o-7b3125.mp3",
  "Âm u": "/audio/tro-choi/am-u-8b685f.mp3",
  "Âm ư": "/audio/tro-choi/am-u-b3dc0a.mp3",
  "Âm bờ": "/audio/tro-choi/am-bo-97764b.mp3",
  "Âm cờ": "/audio/tro-choi/am-co-a386f7.mp3",
  "Âm dờ": "/audio/tro-choi/am-do-a15ce7.mp3",
  "Âm đờ": "/audio/tro-choi/am-do-8a83da.mp3",
  "Âm gờ": "/audio/tro-choi/am-go-ba0a1a.mp3",
  "Âm hờ": "/audio/tro-choi/am-ho-4d0f23.mp3",
  "Âm lờ": "/audio/tro-choi/am-lo-58a125.mp3",
  "Âm mờ": "/audio/tro-choi/am-mo-5b6f2c.mp3",
  "Âm nờ": "/audio/tro-choi/am-no-7a509a.mp3",
  "Âm pờ": "/audio/tro-choi/am-po-e90939.mp3",
  "Âm rờ": "/audio/tro-choi/am-ro-8cef3b.mp3",
  "Âm sờ": "/audio/tro-choi/am-so-98eb5c.mp3",
  "Âm tờ": "/audio/tro-choi/am-to-bc9b46.mp3",
  "Âm vờ": "/audio/tro-choi/am-vo-ae4bb3.mp3",
  "Âm xờ": "/audio/tro-choi/am-xo-956bb7.mp3",
  "bò": "/audio/tro-choi/bo-b6ebd2.mp3",
  "cá": "/audio/tro-choi/ca-0d601d.mp3",
  "gà": "/audio/tro-choi/ga-1402f4.mp3",
  "mèo": "/audio/tro-choi/meo-2799e1.mp3",
  "chó": "/audio/tro-choi/cho-aef271.mp3",
  "vịt": "/audio/tro-choi/vit-8585a0.mp3",
  "voi": "/audio/tro-choi/voi-010608.mp3",
  "khỉ": "/audio/tro-choi/khi-e5af87.mp3",
  "thỏ": "/audio/tro-choi/tho-0e51c5.mp3",
  "rùa": "/audio/tro-choi/rua-fdd2bd.mp3",
  "ong": "/audio/tro-choi/ong-ddf10d.mp3",
  "cua": "/audio/tro-choi/cua-c85207.mp3",
  "dê": "/audio/tro-choi/de-54b91f.mp3",
  "ngựa": "/audio/tro-choi/ngua-ab1344.mp3",
  "nhà": "/audio/tro-choi/nha-992297.mp3",
  "xe": "/audio/tro-choi/xe-956f8a.mp3",
  "cây": "/audio/tro-choi/cay-7c1e84.mp3",
  "lá": "/audio/tro-choi/la-f742f5.mp3",
  "trăng": "/audio/tro-choi/trang-ea1a82.mp3",
  "mưa": "/audio/tro-choi/mua-38e202.mp3",
  "kem": "/audio/tro-choi/kem-9f7b0c.mp3",
  "trứng": "/audio/tro-choi/trung-dfdccc.mp3",
  "sách": "/audio/tro-choi/sach-1bcdb3.mp3",
  "bút": "/audio/tro-choi/but-ce3561.mp3",
  "ghế": "/audio/tro-choi/ghe-a516b2.mp3",
  "cờ": "/audio/tro-choi/co-10c759.mp3",
  "tàu": "/audio/tro-choi/tau-a1f1f2.mp3",
  "chuối": "/audio/tro-choi/chuoi-10ff2c.mp3",
  "nho": "/audio/tro-choi/nho-136351.mp3",
  "cam": "/audio/tro-choi/cam-ad017e.mp3",
  "mũ": "/audio/tro-choi/mu-3a84ef.mp3",
  "không dấu": "/audio/tro-choi/khong-dau-e30e48.mp3",
  "dấu sắc": "/audio/tro-choi/dau-sac-a15b56.mp3",
  "dấu huyền": "/audio/tro-choi/dau-huyen-eaebe1.mp3",
  "dấu hỏi": "/audio/tro-choi/dau-hoi-4f0f49.mp3",
  "dấu ngã": "/audio/tro-choi/dau-nga-35eba0.mp3",
  "dấu nặng": "/audio/tro-choi/dau-nang-a118a3.mp3",
  "Giỏi quá!": "/audio/tro-choi/gioi-qua-354e97.mp3",
  "Đúng rồi!": "/audio/tro-choi/dung-roi-27bb16.mp3",
  "Tuyệt vời!": "/audio/tro-choi/tuyet-voi-5bf321.mp3",
  "Bé làm đúng rồi!": "/audio/tro-choi/be-lam-dung-roi-7d2ee5.mp3",
  "Chưa đúng, bé thử lại nhé.": "/audio/tro-choi/chua-dung-be-thu-lai-nhe-0a6e88.mp3",
  "Đây là gì? Bé chọn chữ đúng nhé.": "/audio/tro-choi/day-la-gi-be-chon-chu-dung-nhe-41537e.mp3",
  "Bé được 0 ngôi sao!": "/audio/tro-choi/be-duoc-0-ngoi-sao-151524.mp3",
  "Bé được 1 ngôi sao!": "/audio/tro-choi/be-duoc-1-ngoi-sao-1cf87e.mp3",
  "Bé được 2 ngôi sao!": "/audio/tro-choi/be-duoc-2-ngoi-sao-ac4557.mp3",
  "Bé được 3 ngôi sao!": "/audio/tro-choi/be-duoc-3-ngoi-sao-f6eff8.mp3",
  "Bé được 4 ngôi sao!": "/audio/tro-choi/be-duoc-4-ngoi-sao-fecb94.mp3",
  "Bé được 5 ngôi sao!": "/audio/tro-choi/be-duoc-5-ngoi-sao-c27c76.mp3",
  "Bé được 6 ngôi sao!": "/audio/tro-choi/be-duoc-6-ngoi-sao-112cb2.mp3",
  "Bé được 7 ngôi sao!": "/audio/tro-choi/be-duoc-7-ngoi-sao-c7c1ee.mp3",
  "Bé được 8 ngôi sao!": "/audio/tro-choi/be-duoc-8-ngoi-sao-173328.mp3",
  "Bé được 9 ngôi sao!": "/audio/tro-choi/be-duoc-9-ngoi-sao-6c41cd.mp3",
  "Bé được 10 ngôi sao!": "/audio/tro-choi/be-duoc-10-ngoi-sao-daab80.mp3",
};
