// TỰ SINH bởi scripts/gen-letter-audio.py — đừng sửa tay, chạy lại script.
// Câu GameShell nói -> file mp3 đọc sẵn bằng Piper (xem docstring script).

export const LETTER_CLIPS: Record<string, string> = {
  "Âm a": "/audio/chu/am-a.mp3",
  "Âm á": "/audio/chu/am-a-trang.mp3",
  "Âm ớ": "/audio/chu/am-a-mu.mp3",
  "Âm e": "/audio/chu/am-e.mp3",
  "Âm ê": "/audio/chu/am-e-mu.mp3",
  "Âm i": "/audio/chu/am-i.mp3",
  "Âm o": "/audio/chu/am-o.mp3",
  "Âm ô": "/audio/chu/am-o-mu.mp3",
  "Âm ơ": "/audio/chu/am-o-moc.mp3",
  "Âm u": "/audio/chu/am-u.mp3",
  "Âm ư": "/audio/chu/am-u-moc.mp3",
  "Âm bờ": "/audio/chu/am-b.mp3",
  "Âm cờ": "/audio/chu/am-c.mp3",
  "Âm dờ": "/audio/chu/am-d.mp3",
  "Âm đờ": "/audio/chu/am-dd.mp3",
  "Âm gờ": "/audio/chu/am-g.mp3",
  "Âm hờ": "/audio/chu/am-h.mp3",
  "Âm lờ": "/audio/chu/am-l.mp3",
  "Âm mờ": "/audio/chu/am-m.mp3",
  "Âm nờ": "/audio/chu/am-n.mp3",
  "Âm pờ": "/audio/chu/am-p.mp3",
  "Âm rờ": "/audio/chu/am-r.mp3",
  "Âm sờ": "/audio/chu/am-s.mp3",
  "Âm tờ": "/audio/chu/am-t.mp3",
  "Âm vờ": "/audio/chu/am-v.mp3",
  "Âm xờ": "/audio/chu/am-x.mp3",
  "Giỏi quá!": "/audio/chu/khen-1.mp3",
  "Đúng rồi!": "/audio/chu/khen-2.mp3",
  "Tuyệt vời!": "/audio/chu/khen-3.mp3",
  "Bé làm đúng rồi!": "/audio/chu/khen-4.mp3",
  "Chưa đúng, bé thử lại nhé.": "/audio/chu/thu-lai.mp3",
  "Bé được 0 ngôi sao!": "/audio/chu/ket-qua-0.mp3",
  "Bé được 1 ngôi sao!": "/audio/chu/ket-qua-1.mp3",
  "Bé được 2 ngôi sao!": "/audio/chu/ket-qua-2.mp3",
  "Bé được 3 ngôi sao!": "/audio/chu/ket-qua-3.mp3",
  "Bé được 4 ngôi sao!": "/audio/chu/ket-qua-4.mp3",
  "Bé được 5 ngôi sao!": "/audio/chu/ket-qua-5.mp3",
  "Bé được 6 ngôi sao!": "/audio/chu/ket-qua-6.mp3",
  "Bé được 7 ngôi sao!": "/audio/chu/ket-qua-7.mp3",
  "Bé được 8 ngôi sao!": "/audio/chu/ket-qua-8.mp3",
  "Bé được 9 ngôi sao!": "/audio/chu/ket-qua-9.mp3",
  "Bé được 10 ngôi sao!": "/audio/chu/ket-qua-10.mp3",
};
